### ISSUE TITLE
Esp-idf build does not include linker scripts or single partition image

### ISSUE THREAD

**Issue by ccrause** [michael-ring/espsdk4fpc#5]
In commit 0788700e94e228 the following lines were commented in buildsdk.sh:
```
#cp ./build/esp32/esp32.project.ld     $OUTPUTDIR/lx6
#cp ./build/esp32/esp32_out.ld         $OUTPUTDIR/lx6
```
This will cause automatic regeneration of the linker scripts for each new project when compiled.  

```
#cp ./build/partitions_singleapp.bin   $OUTPUTDIR/lx6
```
This partition image is useful for large non-OTA projects, since the partition can handle double the size compared to the two partition OTA image.

It s not clear why these files are not included in the distribution for esp32?

**Comment by michael-ring** [comment]
I commented out files that were not generated during build, are you sure they were generated?
Will try now.

**Comment by ccrause** [comment]
I still see them in my espsdk4fpc lx6 folder, where I tested the build script.  Hopefully they are not really missing on your side...

**Comment by michael-ring** [comment]
Nope, they seem to be available. Thank you for the hint!
