### ISSUE TITLE
Philosophy for debug/release libraries?

### ISSUE THREAD

**Issue by ccrause** [michael-ring/espsdk4fpc#8]
Currently the debug library folder does not contain all libraries required to link. At least the compiler supplied libraries are missing and requires adding the parent folder to the library search path.  This then creates a conflict as both release and debug versions of the SDK are visible to the compiler.

My suggestion is to treat each option as equal, so create bot release and debug folders at the same folder level.  Then each folder should contain all files affected by the sdkconfig settings.  Common files such as the partition images and prebuild libraries (toolchain supplied and SDK supplied) should then be moved out to a different folder so that changing from a release to a debug build should involve only changing one folder name.

A tentative new folder structure:
```
/lx6/debug/   (contains compiled libraries, generated linker scripts and bootloader)
/lx6/release/ (contains compiled libraries, generated linker scripts and bootloader)
/lx6/esp32    (contains controller specific toolchain and SDK prebuilt libraries such as libc and libxt_hal)
/lx6/esp32/psram    (contains controller specific prebuilt toolchain libraries)
/lx6/         (contains partition and ota images)
```

And of course a similar layout for esp8266.

Any thoughts/comments?

**Comment by michael-ring** [comment]
Please check if contents of devel branch work for you

**Comment by michael-ring** [comment]
Continued in 
https://github.com/michael-ring/espsdk4fpc/issues/11
