### ISSUE TITLE
Error when creating venv when calling esptool.py

### ISSUE THREAD

**Issue by ccrause** [michael-ring/espsdk4fpc#9]
Verbose: IDF_PATH is /home/christo/espsdk4fpc2/5.0.6/esp32c3/riscv32-binutils-amd64-linux/esp-idf-5.0.6
Debug: Requirement already satisfied: pip in /home/christo/espsdk4fpc2/5.0.6/esp32c3/riscv32-binutils-amd64-linux/esp-idf-5.0.6/venv/lib/python3.10/site-packages (22.0.2)
Debug: Collecting pip
Debug:   Using cached pip-24.0-py3-none-any.whl (2.1 MB)
Debug: Installing collected packages: pip
Debug:   Attempting uninstall: pip
Debug:     Found existing installation: pip 22.0.2
Debug:     Uninstalling pip-22.0.2:
Debug:       Successfully uninstalled pip-22.0.2
Debug: Successfully installed pip-24.0
Error: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/christo/espsdk4fpc2/5.0.6/esp32c3/riscv32-binutils-amd64-linux/esp-idf-5.0.6/requirements.txt'
Debug: Setting up modules for venv failed
Debug: please create an issue on https://github.com/michael-ring/espsdk4fpc/issues and paste the following output:
Error: ERROR: Could not open requirements file: [Errno 2] No such file or directory: '/home/christo/espsdk4fpc2/5.0.6/esp32c3/riscv32-binutils-amd64-linux/esp-idf-5.0.6/requirements.txt'

**Comment by ccrause** [comment]
This file moved to esp-idf/tools/requirements/requirements.core.txt since v5.0.  Copying this file to esp-idf/requirements.txt fixes the above problem for esp-idf v5.0.6 and leads to successful compilation and linking and running of the esp32c3 demo. :smiley:

**Comment by michael-ring** [comment]
Hmm... I already had a workarround in place but yours is better... Can you please pull & check?

**Comment by ccrause** [comment]
I cannot test right now, but I suspect you also need to handle the alternative location and name for the requirements file in buildsdk.sh around here https://github.com/michael-ring/espsdk4fpc/blob/3b39b0e76673b08e0e529762b4091329b5e54aca/buildsdk.sh#L211 and here https://github.com/michael-ring/espsdk4fpc/blob/3b39b0e76673b08e0e529762b4091329b5e54aca/buildsdk.sh#L256
